# Makefile — Aptos Core developer build utilities
#
# sccache targets:
#   make sccache-setup       Install sccache + generate .sccache.env for this checkout
#   make sccache-setup-rust  Same, but also wrap rustc (disables incremental compilation)
#   make sccache-check       Verify sccache is configured and working
#   make sccache-stats       Show sccache hit/miss statistics
#   make sccache-clean       Stop sccache server and clear local cache
#
# After running `make sccache-setup`, add this to ~/.zshrc or ~/.bashrc:
#   source /path/to/aptos-core/.sccache.env
#
# If you have multiple checkouts, source each one's .sccache.env — the
# Makefile automatically appends to SCCACHE_BASEDIRS so all checkouts
# share cache hits.

SHELL := /bin/bash
PROJECT_ROOT := $(shell pwd)
SCCACHE_ENV := $(PROJECT_ROOT)/.sccache.env

# ─── sccache setup ───────────────────────────────────────────────────────────

.PHONY: sccache-setup
sccache-setup: sccache-install $(SCCACHE_ENV)
	@echo ""
	@echo "Done! Add this to your shell profile (~/.zshrc or ~/.bashrc):"
	@echo ""
	@echo "  source $(SCCACHE_ENV)"
	@echo ""
	@echo "Then restart your shell or run: source $(SCCACHE_ENV)"

.PHONY: sccache-setup-rust
sccache-setup-rust: INCLUDE_RUST=1
sccache-setup-rust: sccache-install $(SCCACHE_ENV)
	@echo ""
	@echo "Done! Add this to your shell profile (~/.zshrc or ~/.bashrc):"
	@echo ""
	@echo "  source $(SCCACHE_ENV)"
	@echo ""
	@echo "Then restart your shell or run: source $(SCCACHE_ENV)"

# ─── Install sccache ─────────────────────────────────────────────────────────

.PHONY: sccache-install
sccache-install:
	@if command -v sccache &>/dev/null; then \
		echo "sccache already installed: $$(sccache --version)"; \
	else \
		echo "Installing sccache..."; \
		case "$$(uname -s)" in \
			Darwin) \
				if command -v brew &>/dev/null; then \
					brew install sccache; \
				else \
					echo "Homebrew not found. Install via: cargo install sccache --locked"; \
					exit 1; \
				fi;; \
			Linux) \
				cargo install sccache --locked;; \
			*) \
				echo "Unsupported platform: $$(uname -s)"; \
				exit 1;; \
		esac; \
		echo "Installed: $$(sccache --version)"; \
	fi

# ─── Generate .sccache.env ───────────────────────────────────────────────────

$(SCCACHE_ENV): FORCE
	@echo "Generating $(SCCACHE_ENV) ..."
	@{ \
		echo "# Auto-generated by: make sccache-setup"; \
		echo "# Checkout: $(PROJECT_ROOT)"; \
		echo "# Re-run 'make sccache-setup' to regenerate."; \
		echo ""; \
		echo "# ── S3 shared cache ──"; \
		echo "export SCCACHE_BUCKET=aptos-sccache-shared"; \
		echo "export SCCACHE_REGION=us-west-2"; \
		echo "export SCCACHE_S3_USE_SSL=true"; \
		echo ""; \
		echo "# ── Path normalization (enables sharing across checkouts) ──"; \
		echo "# Appends this checkout to SCCACHE_BASEDIRS so multiple checkouts"; \
		echo "# share the same cache. Each checkout's .sccache.env adds its own path."; \
		echo 'if [ -z "$${SCCACHE_BASEDIRS:-}" ]; then'; \
		echo "  export SCCACHE_BASEDIRS=$(PROJECT_ROOT)"; \
		echo "else"; \
		echo '  case ":$$SCCACHE_BASEDIRS:" in'; \
		echo "    *\":$(PROJECT_ROOT):\"*) ;;"; \
		echo "    *) export SCCACHE_BASEDIRS=\"\$$SCCACHE_BASEDIRS:$(PROJECT_ROOT)\" ;;"; \
		echo "  esac"; \
		echo "fi"; \
		echo ""; \
		echo "# ── C/C++ compiler wrapping (~95s savings on -sys crates) ──"; \
		echo 'export CC="sccache cc"'; \
		echo 'export CXX="sccache c++"'; \
	} > $(SCCACHE_ENV)
	@if [ "$(INCLUDE_RUST)" = "1" ]; then \
		{ \
			echo ""; \
			echo "# ── Rust compiler wrapping (disables incremental compilation) ──"; \
			echo "export RUSTC_WRAPPER=sccache"; \
		} >> $(SCCACHE_ENV); \
	fi
	@echo "Generated: $(SCCACHE_ENV)"

FORCE:

# ─── Verify setup ────────────────────────────────────────────────────────────

.PHONY: sccache-check
sccache-check:
	@echo "=== sccache setup check ==="
	@echo ""
	@# Check sccache installed
	@if command -v sccache &>/dev/null; then \
		echo "[OK] sccache installed: $$(sccache --version)"; \
	else \
		echo "[FAIL] sccache not found. Run: make sccache-setup"; \
		exit 1; \
	fi
	@echo ""
	@# Check .sccache.env exists
	@if [ -f "$(SCCACHE_ENV)" ]; then \
		echo "[OK] $(SCCACHE_ENV) exists"; \
	else \
		echo "[FAIL] $(SCCACHE_ENV) not found. Run: make sccache-setup"; \
		exit 1; \
	fi
	@echo ""
	@# Check env vars are set
	@if [ -n "$${SCCACHE_BUCKET:-}" ]; then \
		echo "[OK] SCCACHE_BUCKET=$$SCCACHE_BUCKET"; \
	else \
		echo "[WARN] SCCACHE_BUCKET not set — source $(SCCACHE_ENV) first"; \
	fi
	@if [ -n "$${SCCACHE_BASEDIRS:-}" ]; then \
		echo "[OK] SCCACHE_BASEDIRS=$$SCCACHE_BASEDIRS"; \
	else \
		echo "[WARN] SCCACHE_BASEDIRS not set — source $(SCCACHE_ENV) first"; \
	fi
	@if [ -n "$${CC:-}" ] && echo "$$CC" | grep -q sccache; then \
		echo "[OK] CC=$$CC"; \
	else \
		echo "[WARN] CC not wrapped with sccache"; \
	fi
	@if [ -n "$${CXX:-}" ] && echo "$$CXX" | grep -q sccache; then \
		echo "[OK] CXX=$$CXX"; \
	else \
		echo "[WARN] CXX not wrapped with sccache"; \
	fi
	@if [ -n "$${RUSTC_WRAPPER:-}" ]; then \
		echo "[OK] RUSTC_WRAPPER=$$RUSTC_WRAPPER"; \
	else \
		echo "[INFO] RUSTC_WRAPPER not set (Rust uses incremental compilation)"; \
	fi
	@echo ""
	@# Check AWS credentials (for S3 mode)
	@if [ -n "$${AWS_ACCESS_KEY_ID:-}" ]; then \
		echo "[OK] AWS_ACCESS_KEY_ID is set"; \
	else \
		echo "[WARN] AWS_ACCESS_KEY_ID not set — S3 sharing disabled (local cache only)"; \
	fi
	@echo ""
	@# Check sccache server
	@if sccache --show-stats &>/dev/null; then \
		echo "[OK] sccache server running"; \
		echo ""; \
		sccache --show-stats 2>&1 | head -5; \
	else \
		echo "[INFO] sccache server not running (starts automatically on first compile)"; \
	fi

# ─── Stats and cleanup ───────────────────────────────────────────────────────

.PHONY: sccache-stats
sccache-stats:
	@sccache --show-stats

.PHONY: sccache-clean
sccache-clean:
	@echo "Stopping sccache server..."
	-@sccache --stop-server 2>/dev/null
	@echo "Clearing local sccache cache..."
	@rm -rf "$${HOME}/Library/Caches/Mozilla.sccache/" "$${HOME}/.cache/sccache/"
	@echo "Done. S3 cache is not affected."
