# This workflow tests that the Aptos CLI can be compiled on Windows
name: "Windows CLI Build"

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, opened, synchronize, reopened, auto_merge_enabled]
  # schedule: # NOTE: the schedule is dictated by PIES

jobs:
  windows-build:
    runs-on: windows-2025
    if: | # Only run on each PR once an appropriate event occurs
      (
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'schedule' ||
        contains(github.event.pull_request.labels.*.name, 'CICD:run-windows-tests')
      )
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Fetch all git history for accurate target determination

      - name: Set up minimal CLI build environment
        run: PowerShell -ExecutionPolicy Bypass -File scripts/cli/minimal_cli_build.ps1

      # This action will cache ~/.cargo and ./target (or the equivalent on Windows in
      # this case). See more here:
      # https://github.com/Swatinem/rust-cache#cache-details
      - name: Run cargo cache
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # pin@v2.7.8

      # Output the changed files
      - name: Output the changed files
        run: cargo x changed-files -vv
        shell: bash

      # Output the affected packages
      - name: Output the affected packages
        run: cargo x affected-packages -vv
        shell: bash

      # Build and test the Aptos CLI (if it has changed)
      - name: Build and test the CLI
        run: cargo x targeted-cli-tests -vv
        shell: bash
